# Generated by Django 4.1.7 on 2023-03-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('remarks', models.TextField()),
                ('amount', models.FloatField()),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
